### ISSUE TITLE
No sourcemaps when running on Android emulator

### ISSUE THREAD

**Issue by b99andla** [jhen0409/react-native-debugger#189]
I cant debug the sourcemaps from my project when running my project in debug mode in the Android emulator. It works fine when running debug mode from XCode and iOS emulator, then I can access my codefiles via the sourcemaps. 

When running the project in Android, I cant view my original files via sourcemaps. It works if I do the debbugging in Chrome directly instead of React Native Debugger. Ive also tried reinstalling React Native Debugger. 

React Native Debugger app version: 0.7.13
React Native version: 0.47.1
Platform: Android
Is real device of platform: Android emulator
Operating System: macOS

**Comment by jhen0409** [comment]
Is `Enable JavaScript source maps` disabled on devtools settings? Reinstalling the app doesn't reset the setting. You can try to `Restore defaults and settings` on devtools settings.

**Comment by b99andla** [comment]
Thanks @jhen0409 "Restore defaults" did the trick! This can be closed!

**Comment by steveccable** [comment]
@jhen0409 I am having this same issue, and have checked the `Enable JavaScript source maps` setting on and off with no change.  Similarly, `Restore defaults and reload` has not helped this at all (and, curiously, doesn't actually reload the app.  I have to manually close and reopen, but I can tell that it is restoring at least the appearance theme, making me think it must be doing _something_).

Similar to the OP, I can see my sourcemaps fine when debugging in Chrome as well as when debugging iOS.

For reference, I am using
Debugger app version: 0.7.13
RN Version: 0.53.3
Platform: Android
Real or emulator: emulator
OS: macOS High Sierra 10.13.2

**Comment by xanderberkein** [comment]
I have the same issue. Started happening after I upgraded from react-native 0.53.0 to 0.54.0

**Comment by jhen0409** [comment]
It may starting from RN 0.52, the default chrome debugger start using the new Delta bundler, and I have noticed the older bundler didn't load source map successfully. I don't know if it's bug, but it's time to support Delta bundler for newer RN versions, please tracking #158.

**Comment by alexfoxy** [comment]
I have this issue also. Using chrome debugger for now.

**Comment by jhen0409** [comment]
It should be fixed in #211, I'll release the new version later.

**Comment by alexfoxy** [comment]
@jhen0409 how can I build from the master source?

**Comment by jhen0409** [comment]
@alexfoxy you can follow the [documentation](https://github.com/jhen0409/react-native-debugger/blob/master/docs/contributing.md).

**Comment by steveccable** [comment]
FYI, this is still broken for me on RN 0.55.2.  Since it looks like you had releases between the fix went in and now, I'm guessing it probably got fixed and then re-broken on a later version of RN.
