### ISSUE TITLE
Debugger blocks connection to firebase

### ISSUE THREAD

**Issue by SirKadogan** [jhen0409/react-native-debugger#350]
Everything is working fine when debugger is disconnected. When I connect the debugger, I can't reach firebase at all. It seems firebase is the only conflict there. 

What could it be?

React Native Debugger app version: 0.9.8
React Native version0.58.0
Platform:Android
Is real device of platform: Real Device
Operating System: Windows

**Comment by yosukapro** [comment]
Same issue. Any solution?

**Comment by SirKadogan** [comment]
It's been a while since I fixed it and I can't recall exactly what I did, but I believe I updated both react-native-debugger and React Native to the latest versions. It's all working fine for me now. 
I think I reinstalled the debugger from scratch as well.

Let me know if that helped you :)

**Comment by jhen0409** [comment]
is it [firebase](https://www.npmjs.com/package/firebase) or [react-native-firebase](https://www.npmjs.com/package/react-native-firebase)? In my experience, it may got some timer issue on pure JS version of firebase.

**Comment by ThomasFindlay** [comment]
I started to have the same issue a few months ago and had to switch to a different debugger. I checked recently and the connectivity issue was still there. @jhen0409 it happens with react-native-firebase.

**Comment by dwaynelavon** [comment]
I am still having this issue now. It starts when I use the debugger with firebase and then I have connection issues until I restart.

**Comment by hani-q** [comment]
Stuck here too.. really need the debugger to work any updates on this guys ? 

![image](https://user-images.githubusercontent.com/3755330/76218025-851f7f00-6224-11ea-9d2a-0d3793dfbf6f.png)

**Comment by hani-q** [comment]
> is it [firebase](https://www.npmjs.com/package/firebase) or [react-native-firebase](https://www.npmjs.com/package/react-native-firebase)? In my experience, it may got some timer issue on pure JS version of firebase.

For me its React-native, expo and Firebase JS SDK

**Comment by hani-q** [comment]
Issue fixed for me. I was using older release of the debugger to make it work on windows (Which is a separate issue as dark mode permits it from opening) so after figuring that out and moving to the latest version all firebase request are working for me

**Comment by SirKadogan** [comment]
Funny that I ran into the same issue more than a year later while working on another project. I didn't even remember this.

Apparently the problem was that my computer and my phone were unsynced by a few seconds.

Here's how I fixed it this time: (windows 10)

1. Date and time settings on your computer
2. Under 'synchronize your clock' -> Sync now.
