### ISSUE TITLE
Console disappears and remote debugging stops work (0.10.0)

### ISSUE THREAD

**Issue by inferusvv** [jhen0409/react-native-debugger#405]
React Native Debugger app version: 0.10.0
React Native version: 0.60.5
Platform: iOS, Android
Is real device of platform: Yes/No
Operating System: macOS 10.14.6

I've upgrade RND to 0.10.0 version and now have a problem that console is disappeares and bundle can't be loaded on phone/simulator when remote debugging is on. Issue is everywhere (simulator/real device, android/iOS). It happens time-to-time.

<img width="1319" alt="Снимок экрана 2019-09-21 в 22 52 07" src="https://user-images.githubusercontent.com/3227120/65378578-ea0d0a00-dcc2-11e9-9056-7f0301814d6c.png">

Stuck like this:
<img width="557" alt="Снимок экрана 2019-09-21 в 22 53 40" src="https://user-images.githubusercontent.com/3227120/65378579-eaa5a080-dcc2-11e9-9752-ca506fd8b0f1.png">

**Comment by shamilovtim** [comment]
Ever since 1 update ago I have been having this issue repeatedly. Every 5 minutes I have to restart the debugger.

**Comment by rarira** [comment]
0.10.1 has the same issue...

**Comment by shamilovtim** [comment]
This gets you 0.9.14:

```
brew cask uninstall react-native-debugger
```

```
brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/f6db4e3e6c2a773bc2967db5819118299b8a60a1/Casks/react-native-debugger.rb
```

**Comment by CoenWarmer** [comment]
Also experiencing this on 0.10.1... Any outlook on a fix?

**Comment by mirague** [comment]
Same thing here, will downgrade to 0.9.14 thanks @shamilovtim !

**Comment by schumannd** [comment]
This not only causes the debugger to break, but also causes the app to not load. Major bug.

**Comment by flashman2** [comment]
Same here...

**Comment by minhchienwikipedia** [comment]
Same here, downgrade work for me. But I think we should resolve this issue asap!

**Comment by dquessenberry** [comment]
Same here. RNDebugger freeze about every 10-30 minutes and prevents the simulator from loading. Must quit RNDebugger and restart. This is definitely a major bug and I will downgrade for now. Love this tool though!

**Comment by elkinjosetm** [comment]
Yep, same here, but I've found that you don't need to restart the whole debugger, just close the inspector, and open it up again. `cmd+i` to close it, `cmd+i` to open it up again. It's faster than close the app and then open it up again IMO

**Comment by shchu** [comment]
> Yep, same here, but I've found that you don't need to restart the whole debugger, just close the inspector, and open it up again. `cmd+i` to close it, `cmd+i` to open it up again. It's faster than close the app and then open it up again IMO

This work for me, but the hotkey should be `cmd + option + i`

**Comment by MacKentoch** [comment]
Appart from helpful workarounds (downgrading or `cmd + option + i`), is there a blocking point (*ex: from react-native, metro...*)?

Not bashing at all (*I love this tool and thank all people involved*) but just want to simply know about.

**Comment by inferusvv** [comment]
0.10.2. Still exists

**Comment by shamilovtim** [comment]
Hey just wanted to clarify that anyone can avoid this issue by downgrading to v0.9.14 for now. I listed the instructions to do so up above!

**Comment by GunnarAK** [comment]
0.10.4. Still exists

**Comment by mirague** [comment]
How's this looking in `0.10.5`? Didn't see any mention in the release notes.

**Comment by jean-marc-cp** [comment]
I've not had one since upgrading. Don't think that's conclusive though.

**Comment by inferusvv** [comment]
I am on 0.10.4 and had it only 1 time this week. Very interesting what causes this issue

**Comment by drewandre** [comment]
Hate to add to this issue without any actual solutions but just wanted to confirm that I'm seeing this in 0.10.5, and I'm also seeing this new issue where the debugger freezes entirely and requires a force quit/restart. This is less frequent - I maybe see 5 or 6 of the chrome console crashes that have been described in this issue (solved by toggle developer console CMD+OPT+i on mac) before it freezes entirely.

I'm wondering if anyone else is experiencing this issue? And is there a way we can help the maintainer by providing crash logs? Or are these automatically recorded somewhere?

**Comment by bockc** [comment]
I'm on 0.10.5 and I can confirm that this issue is still there. I don't know what causes this issue. Nothing's wrong when I'm not debugging, there's no endless loop or whatever, but as soon as I enable the debugger at some point in the code it freezes and causes this issue.

**Comment by sorakrisc** [comment]
this problem still persist in 0.10.6

**Comment by mirague** [comment]
This temporary workaround was posted in another similar issue, which is to have the debugger reload itself every N tries.

Go to `Debugger > Open Config File` and add these lines:
```
  // Refresh devtools when doing JS reload every N times. (-1 for disabled)
  // This can effectively avoid possible memory leaks (Like
  // https://github.com/jhen0409/react-native-debugger/issues/405) in devtools.
  timesJSLoadToRefreshDevTools: 5,
```

**Comment by AnthonyWard** [comment]
I've created a fix & PR here https://github.com/jhen0409/react-native-debugger/pull/531

Basically, electron needs to be updated to at least `7.1.14`, as that includes this fix: https://github.com/electron/electron/pull/22338

**Comment by ghasemikasra39** [comment]
Facing the same issue on `0.11.5`. Any solution ?

**Comment by MrAlexWeber** [comment]
Wanted to report that this issue is persisting in `0.10.7` as well, but I'm willing to live with the workarounds & forks for now 😂

**Comment by Asinox** [comment]
Well, version 1.1.0 still facing the same issue.

**Comment by ghasemikasra39** [comment]
Facing the same issue on 0.11.6 on both mac and windows
