### ISSUE TITLE
Network inspector failing all requests (fetch)

### ISSUE THREAD

**Issue by canpoyrazoglu** [jhen0409/react-native-debugger#431]
React Native Debugger app version: 0.10.3
React Native version: 0.61.4
Platform: iOS
Is real device of platform: Simulator 11.0.1
Operating System: macOS

When I've got network inspector disabled everything works fine (and my app does API requests successfully). Today I needed to examine a problematic API request and enabled network inspector. Immediately all my (including previously working ones) requests started to fail with `SyntaxError: Unexpected token o in JSON at position 1`. This looks like something deeper affecting multiple components of the debugger as I've opened a very similar issue https://github.com/jhen0409/react-native-debugger/issues/426 which has the same error but with UI inspector when trying to view a component with percentage margins on UI inspector, irrelevant from the Network Inspector. I've also seen https://github.com/jhen0409/react-native-debugger/issues/190 but on that issue users are getting 401 errors whereas I'm getting a JSON parser error.

**Comment by IlyaGulya** [comment]
Same for me

**Comment by johnborges** [comment]
I'm also encountering this bug.

React Native Debugger app version: 0.10.3
React Native version: 0.61.4
Platform: iOS
Is real device of platform: Simulator 13.1
Operating System: macOS 10.15.1

**Comment by nvthai** [comment]
@canpoyrazoglu @IlyaGulya @johnborges It is fixed in the latest release [v0.10.4](https://github.com/jhen0409/react-native-debugger/tree/v0.10.4)

Check it out!

**Comment by peter-dragon** [comment]
@nvthai Today I've updated to `v0.10.4` and the problem just started, wasn't there in `v0.10.3`

Platform: iOS
React Native version: 0.60.5
Is real device of platform: Simulator 12.4
Operating System: macOS 10.14.6

**Comment by peter-dragon** [comment]
@nvthai `v0.10.4` hasn't fixed the issue, the last working version for me is `v0.10.2`

React Native Debugger app version: 0.10.3 and 0.10.4
React Native version: 0.60.5
Platform: iOS
Is a real device of the platform: Simulator 12.4
Operating System: macOS 10.14.6

**Comment by canpoyrazoglu** [comment]
@jhen0409 I can confirm that this issue has been fixed for me with 0.10.4. 
@peter-dragon can you, if possible, try again with the latest RN version?

**Comment by johnborges** [comment]
> @nvthai `v0.10.4` hasn't fixed the issue, the last working version for me is `v0.10.2`
> 
> React Native Debugger app version: 0.10.3 and 0.10.4
> React Native version: 0.60.5
> Platform: iOS
> Is a real device of the platform: Simulator 12.4
> Operating System: macOS 10.14.6

I can confirm the same. 0.10.4 still not working for me either.
